---
- hosts: jenkins 
  tasks:
  - name: Run benchmark script 
    command: "{{ansible_env.HOME}}/linxapp/benchmark.bash" 
    register: benchmark 

  - debug: msg="{{item}}"
    whith_items: benchmark.stdout_lines
    when: result.stdout_lines


